languageCode = 'en-us'
title = 'Saggie Haim - Automate Everything'
author = "Saggie Haim"
DefaultContentLanguage = "en"
copyright = "Saggie Haim"
paginate = 10
# SEO keywords and description for your site.
keywords = "Saggiehaim, PowerShell, Azure, Saggie Haim, Automate Everything, Microsoft Sentinel"
subtitle = "Powershell, DevOps, Security, and automation."
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
enableRobotsTXT = true
enableEmoji = true


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

